### ISSUE TITLE
Notification for new comments is missing a space before the product name

### ISSUE THREAD

**Issue by flodolo** [MikkCZ/pontoon-addon#124]
<img width="531" alt="Schermata 2020-03-21 alle 15 32 10" src="https://user-images.githubusercontent.com/3644868/77228691-49bc7300-6b89-11ea-9a00-db6560fcce18.png">

I couldn't figure out why from a quick look at the code, given that Pontoon's notification is correctly spaced.

<img width="356" alt="Schermata 2020-03-21 alle 15 33 51" src="https://user-images.githubusercontent.com/3644868/77228706-62c52400-6b89-11ea-80eb-fa5c6b4be060.png">

**Comment by MikkCZ** [comment]
Thanks for reporting. I noticed few other bugs for the comments notification. I will fix them today and release a version later during the weekend.
