### ISSUE TITLE
Remove webdashboard code, update URL for mozilla-l10n-query

### ISSUE THREAD

**Issue by flodolo** [MikkCZ/pontoon-addon#126]
I plan to decommission the l10n community server by the end of the year. For mozilla-l10n-query, you can use https://flod.org/mozilla-l10n-query/
https://github.com/MikkCZ/pontoon-addon/blob/f42807959b6bf2c685b87926ed1ac0c5a46b99b8/src/packages/background/src/RemotePontoon.js#L258

I also noticed there's still code mentioning the webdashboard, but that has been removed a while ago
https://github.com/MikkCZ/pontoon-addon/blob/a506c9ce6fa3d6fecdc4943d3d96b7cfe33738a7/src/packages/commons/src/RemoteLinks.js#L41

**Comment by MikkCZ** [comment]
Thank you. I will try to do the necessary updated by the end of next week.

**Comment by flodolo** [comment]
> Thank you. I will try to do the necessary updated by the end of next week.

Note that it's far from urgent, I filed mostly to avoid forgetting about it ;-)
