### ISSUE TITLE
Rename Pontoon Tools to Pontoon Add-on

### ISSUE THREAD

**Issue by MikkCZ** [MikkCZ/pontoon-addon#72]
One of the prerequisites for promoting Pontoon Tools to more users is to rename the add-on to something more explicit and better self describing. "Tools" can be actually anything and when speaking or writing about Pontoon Tools, it may not be clear whether the speaker means the add-on or just the app itself or some of its features.

blocks #79

TODO
- [x] #118 update name in code
- [x] update wiki
- [x] rename the repository
- [x] update links to/from wiki and the repo
- [x] verify CI and Code Climate are working
- [x] update add-on listings on AMO and Chrome Web Store

**Comment by MikkCZ** [comment]
There was an idea of making Pontoon app itself extensible. We should rename Pontoon Tools to something that won't be confusing for users, when extensions for the Pontoon app are introduced in past.

**Comment by mathjazz** [comment]
I believe calling it `Pontoon Add-On` will make it appear more official.
