### ISSUE TITLE
SUMO funcionality broken in Nightly

### ISSUE THREAD

**Issue by Delphine** [MikkCZ/pontoon-addon#743]
### Steps to reproduce
1. Open Nightly v119
2. go to support.mozilla.org
3. Look at the Pontoon image in the URL bar

### Actual behavior

Pontoon logo is greyed out (vs green on release). When you click on it, nothing happens (so, you don't get the three usual options).

### Expected behavior
Pontoon logo is green and you can chose between three options and click on them (see image below for expected behavior)
![Screenshot 2023-08-30 at 11 12 11 AM](https://github.com/MikkCZ/pontoon-addon/assets/399020/7e26dc4a-835e-4ea7-8f14-364a58c4c481)

**Comment by MikkCZ** [comment]
Hi Delphine.

I tried with build ID `20230831214652` with both existing and a clean profile and I cannot reproduce that behavior. With dark Firefox theme the icon is indeed grey (but with light it's green), but regardless of the color, when I click the icon in the address bar, it works and shows the options.

Can you please open the debugging tools and share if something appears in the console?

- In a new tab, open `about:debugging#/runtime/this-firefox`.
- Next to _Pontoon Add-on_ in the extensions list, click _Inspect_.
- A new window should open closely resembling regulard website DevTools. In there, open the _Console_ tab.
- Switch to the main Firefox window and open https://support.mozilla.org/ in a new tab.
- Try click the icon in the address bar.
- Switch to the other window and look into the console, if any error show up there.

**Comment by Delphine** [comment]
I still have the same issue as reported. Here's what I got:
<img width="994" alt="Screenshot 2023-09-02 at 7 20 04 AM" src="https://github.com/MikkCZ/pontoon-addon/assets/399020/af74864d-a785-40ba-bbd9-7c18965b4dd0">

(note I'm off until Sept 19, so probably won't be able to help much more until then)

**Comment by MikkCZ** [comment]
The CORS error looks suspicious. Particulary because the request to `flod.org` (loads Bugzilla components for locales) is executed from the background script. I will need to check how CORS is applied to background scripts, and if I need to add an extra permission for that. It just might be the extension obtains it as a side-effect of another action, which did not happen for your installation.

The `can't access property "name"` error might just be the result of it, where the does not expect the Bugzilla component won't be available.

**Comment by MikkCZ** [comment]
If what I wrote is correct, the context button should be inactive for you on all pages, including mozilla.org, Common Voice or Firefox Monitor. Is that so?

**Comment by Delphine** [comment]
That is absolutely correct!

**Comment by MikkCZ** [comment]
Hi @Delphine .

I am about to publish versions 4.11.2, which I hope will fix this issue. Can you please verify, when it's available? Alternatively, it [can be downloaded here (unsigned)](https://github.com/MikkCZ/pontoon-addon/releases/download/v4.11.2/pontoon_add-on-4.11.2-mozilla.zip) and installed via `about:debugging`.

**Comment by Delphine** [comment]
Hmm so I installed it as a temporary add-on, and checked it was version 4.11.2 under Add-ons and Themes, but I still have the exact same issue. I'll try again once the actual update lands, just in case
