### ISSUE TITLE
New badge awarded notification includes the verb "ignore"

### ISSUE THREAD

**Issue by mathjazz** [MikkCZ/pontoon-addon#975]
See https://github.com/mozilla/pontoon/issues/3488.

**Comment by MikkCZ** [comment]
Can Pontoon be adjusted no to include `"ignore"` as verb? How is it handled in Pontoon frontend, so it's not rendered there?

**Comment by mathjazz** [comment]
Pontoon special-cases this type of notifications: 🙈 

https://github.com/harmitgoswami/pontoon/blob/076e825f17cdbdb64cc0603a9d631e79ae710980/translate/src/modules/user/components/UserNotification.tsx#L134
